# Generated by Django 4.1.2 on 2022-10-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakEven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busName', models.TextField()),
                ('units', models.FloatField()),
                ('fixCost', models.FloatField()),
                ('pricePUnit', models.FloatField()),
                ('variable', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busName', models.TextField()),
                ('decison1', models.TextField()),
                ('probability1', models.FloatField()),
                ('cost1', models.FloatField()),
                ('decison2', models.TextField()),
                ('probability2', models.FloatField()),
                ('cost2', models.FloatField()),
                ('decison3', models.TextField()),
                ('probability3', models.FloatField()),
                ('cost3', models.FloatField()),
            ],
        ),
    ]
