# Generated by Django 4.1.2 on 2022-10-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busName', models.TextField()),
                ('yVarName', models.TextField()),
                ('xVarName', models.TextField()),
                ('function', models.TextField()),
            ],
        ),
    ]
