# Generated by Django 4.1.2 on 2022-10-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTools', '0003_forcefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcefield',
            name='coninteger1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='coninteger2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='coninteger3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='coninteger4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='prointeger1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='prointeger2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='prointeger3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='prointeger4',
            field=models.IntegerField(default=0),
        ),
    ]
