# Generated by Django 4.1.2 on 2022-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTools', '0004_forcefield_coninteger1_forcefield_coninteger2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forcefield',
            name='coninteger1',
        ),
        migrations.RemoveField(
            model_name='forcefield',
            name='coninteger2',
        ),
        migrations.RemoveField(
            model_name='forcefield',
            name='coninteger3',
        ),
        migrations.RemoveField(
            model_name='forcefield',
            name='coninteger4',
        ),
        migrations.RemoveField(
            model_name='forcefield',
            name='prointeger1',
        ),
        migrations.RemoveField(
            model_name='forcefield',
            name='prointeger2',
        ),
        migrations.RemoveField(
            model_name='forcefield',
            name='prointeger3',
        ),
        migrations.RemoveField(
            model_name='forcefield',
            name='prointeger4',
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='conLevel1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='conLevel2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='conLevel3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='conLevel4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='proLevel1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='proLevel2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='proLevel3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='proLevel4',
            field=models.TextField(blank=True),
        ),
    ]
