# Generated by Django 4.1.2 on 2022-10-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTools', '0005_remove_forcefield_coninteger1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcefield',
            name='conNumber1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='conNumber2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='conNumber3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='conNumber4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='proNumber1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='proNumber2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='proNumber3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='proNumber4',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
