# Generated by Django 4.1.2 on 2022-10-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTools', '0002_graphing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busName', models.TextField()),
                ('proLevel4', models.TextField()),
                ('proLevel3', models.TextField()),
                ('proLevel2', models.TextField()),
                ('proLevel1', models.TextField()),
                ('conLevel4', models.TextField()),
                ('conLevel3', models.TextField()),
                ('conLevel2', models.TextField()),
                ('conLevel1', models.TextField()),
            ],
        ),
    ]
